### ISSUE TITLE
Extract Function 

### ISSUE THREAD

**Issue by NayanMogra** [rossumai/rossum#23]
Traceback (most recent call last):
  File "C:\Users\LENOVO\Desktop\PDF_Scanner\rossuminvoice.py", line 3, in <module>
    exctracted = rossum.extract('Invoice/QualityHosting.pdf')
AttributeError: module 'rossum' has no attribute 'extract'

though rossum is pipped successfully

**Comment by evelyn9191** [comment]
Hello Nayan, `rossum` library indeed does not have `extract` method. You are probably trying to use the obsolete library that was available in the past, but it is not anymore. To export data from Rossum, you need to write a script for it. We have a couple of samples in different programming languages available on our [Developer Hub ](https://developers.rossum.ai/docs/getting-data-from-rossum)for this purpose.
